/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programs */
        get: operations["list_programs_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Program */
        get: operations["read_program_programs__program_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Analyze */
        post: operations["post_analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/address/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse */
        get: operations["reverse_address_reverse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/address/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_address_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/building": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Building */
        get: operations["read_building_building_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kakao/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kakao Url */
        get: operations["kakao_url_auth_kakao_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kakao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kakao Login */
        post: operations["kakao_login_auth_kakao_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_me_profile_get"];
        /** Write Profile */
        put: operations["write_profile_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Address */
        Address: {
            /** Road */
            road: string;
            /** Jibun */
            jibun?: string | null;
            /** Sidocd */
            sidoCd: string;
            /** Sigungucd */
            sigunguCd: string;
            /** Bjdongcd */
            bjdongCd: string;
            /**
             * Platgbcd
             * @enum {string}
             */
            platGbCd: "0" | "1";
            /** Bun */
            bun: string;
            /** Ji */
            ji: string;
        };
        /** Amount */
        Amount: {
            /** Max */
            max?: number | null;
            /** Short */
            short: string;
            /** Detail */
            detail: string;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Requestid */
            requestId: string;
            classification: components["schemas"]["ClassifyResult"];
            /** Needsconfirm */
            needsConfirm: boolean;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Checkup */
            checkup: components["schemas"]["CheckupItem"][];
            /** Excluded */
            excluded: components["schemas"]["ExcludedItem"][];
            /**
             * Rankerused
             * @enum {string}
             */
            rankerUsed: "llm" | "rules";
            /** Fallbackused */
            fallbackUsed: boolean;
            version: components["schemas"]["VersionInfo"];
        };
        /** Apply */
        Apply: {
            /**
             * State
             * @enum {string}
             */
            state: "always" | "open" | "check" | "closed_next";
            /** Text */
            text: string;
            /** Nexttext */
            nextText?: string | null;
        };
        /** AuthRequest */
        AuthRequest: {
            /** Code */
            code: string;
            /** Redirecturi */
            redirectUri: string;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["AuthUser"];
        };
        /** AuthUrlResponse */
        AuthUrlResponse: {
            /** Url */
            url: string;
        };
        /** AuthUser */
        AuthUser: {
            /** Id */
            id: string;
            /** Nickname */
            nickname: string;
        };
        /** Body_post_analyze_analyze_post */
        Body_post_analyze_analyze_post: {
            /** Household */
            household: string;
            /** Address */
            address?: string | null;
            /** Building */
            building?: string | null;
            /** Overridetype */
            overrideType?: string | null;
            /** Images[] */
            "images[]"?: string[] | null;
        };
        /** Building */
        Building: {
            /** Useaprday */
            useAprDay?: string | null;
            /** Mainpurpose */
            mainPurpose?: string | null;
            /** Grndflrcnt */
            grndFlrCnt?: number | null;
            /** Ugrndflrcnt */
            ugrndFlrCnt?: number | null;
            /** Fetchedok */
            fetchedOk: boolean;
        };
        /** CallPhone */
        CallPhone: {
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
        };
        /** CheckupItem */
        CheckupItem: {
            /** Programid */
            programId: string;
            /**
             * Applystate
             * @enum {string}
             */
            applyState: "always" | "open" | "check" | "closed_next";
        };
        /** ClassifyResult */
        ClassifyResult: {
            /**
             * Type
             * @enum {string}
             */
            type: "leak" | "mold" | "window_insulation" | "heating" | "plumbing" | "safety" | "electric" | "other";
            /** Confidence */
            confidence: number;
            /** Description */
            description: string;
            /**
             * Source
             * @enum {string}
             */
            source: "fake" | "openrouter" | "user";
            /**
             * Overridden
             * @default false
             */
            overridden: boolean;
        };
        /** Display */
        Display: {
            /** Statustext */
            statusText: string;
            /** Incometext */
            incomeText: string;
            /** Buildingagetext */
            buildingAgeText: string;
            /** Regiontext */
            regionText: string;
            /** Conditionstext */
            conditionsText: string;
            /** Supportitemstext */
            supportItemsText: string;
            /** Operatortext */
            operatorText: string;
            /** Howtoapplytext */
            howToApplyText: string;
            /** Periodtext */
            periodText: string;
            /** Sourcestext */
            sourcesText: string;
        };
        /** Eligibility */
        Eligibility: {
            /** Incomemaxpct */
            incomeMaxPct?: number | null;
            /** Tenure */
            tenure?: ("own" | "rent" | "public_rent" | "unknown")[] | null;
            /** Excludehousingbenefitowner */
            excludeHousingBenefitOwner?: boolean | null;
            /** Welfare */
            welfare?: "required_or_low" | null;
            /** Traitsrequired */
            traitsRequired?: ("elderly65" | "disabled" | "welfare")[] | null;
            /** Buildingagemin */
            buildingAgeMin?: number | null;
            /** Approvedbefore */
            approvedBefore?: string | null;
            /** Lowriseonly */
            lowRiseOnly?: boolean | null;
            /** Basementhint */
            basementHint?: boolean | null;
            /** Variants */
            variants?: components["schemas"]["Variant"][] | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExcludedItem */
        ExcludedItem: {
            /** Programid */
            programId: string;
            /** Why */
            why: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            version: components["schemas"]["VersionInfo"];
            /** Mock */
            mock?: string[];
        };
        /** Profile */
        Profile: {
            household?: components["schemas"]["ProfileHousehold"] | null;
            address?: components["schemas"]["ProfileAddress"] | null;
        };
        /**
         * ProfileAddress
         * @description 주소 기본값. 채워진 것만 담는 부분 객체.
         */
        ProfileAddress: {
            /** Road */
            road?: string | null;
            /** Jibun */
            jibun?: string | null;
            /** Sidocd */
            sidoCd?: string | null;
            /** Sigungucd */
            sigunguCd?: string | null;
            /** Bjdongcd */
            bjdongCd?: string | null;
            /** Platgbcd */
            platGbCd?: string | null;
            /** Bun */
            bun?: string | null;
            /** Ji */
            ji?: string | null;
        };
        /**
         * ProfileHousehold
         * @description 가구 기본값. 채워진 것만 담는 부분 객체.
         */
        ProfileHousehold: {
            /** Size */
            size?: number | null;
            /** Income */
            income?: ("le48" | "48_60" | "60_100" | "gt100" | "unknown") | null;
            /** Housingbenefit */
            housingBenefit?: ("yes" | "no" | "unknown") | null;
            /** Tenure */
            tenure?: ("own" | "rent" | "public_rent" | "unknown") | null;
            /** Traits */
            traits?: ("elderly65" | "disabled" | "welfare")[] | string | null;
        };
        /** Program */
        Program: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "in_kind" | "grant" | "loan" | "service" | "reference";
            /**
             * Group
             * @enum {string}
             */
            group: "main" | "checkup" | "reference";
            region: components["schemas"]["Region"];
            /** Problemtypes */
            problemTypes: ("leak" | "mold" | "window_insulation" | "heating" | "plumbing" | "safety" | "electric" | "other")[];
            /** Priority */
            priority: number;
            apply: components["schemas"]["Apply"];
            eligibility: components["schemas"]["Eligibility"];
            /** Toconfirm */
            toConfirm: string[];
            amount: components["schemas"]["Amount"];
            /** Traitbonus */
            traitBonus?: {
                [key: string]: string;
            } | null;
            callPhone?: components["schemas"]["CallPhone"] | null;
            display: components["schemas"]["Display"];
            /** Verificationnotes */
            verificationNotes: string;
            /** Datanote */
            dataNote?: string | null;
            /**
             * Dataconfidence
             * @enum {string}
             */
            dataConfidence: "high" | "mid" | "low";
        };
        /** ProgramsFile */
        ProgramsFile: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 2;
            /** Asof */
            asOf: string;
            /** Builtat */
            builtAt?: string | null;
            /** Source */
            source: string;
            fallbackPhone: components["schemas"]["CallPhone"];
            /** Programs */
            programs: components["schemas"]["Program"][];
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Provider */
            provider: string;
            /** Model */
            model?: string | null;
            /** Prompthash */
            promptHash?: string | null;
        };
        /** RankerInfo */
        RankerInfo: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "llm" | "rules";
            /** Model */
            model?: string | null;
            /** Prompthash */
            promptHash?: string | null;
        };
        /** Recommendation */
        Recommendation: {
            /** Programid */
            programId: string;
            /** Rank */
            rank: number;
            /** Reason */
            reason: string;
            /**
             * Status
             * @enum {string}
             */
            status: "likely" | "maybe";
            /** Toconfirm */
            toConfirm?: string[];
            /**
             * Applystate
             * @enum {string}
             */
            applyState: "always" | "open" | "check" | "closed_next";
            /** Variant */
            variant?: string | null;
        };
        /** Region */
        Region: {
            /** Sido */
            sido?: string | null;
            /** Sigungu */
            sigungu?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Variant */
        Variant: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Amountshort */
            amountShort: string;
            /** Incomemaxpct */
            incomeMaxPct?: number | null;
            /** Traitsany */
            traitsAny?: ("elderly65" | "disabled" | "welfare")[] | null;
            /** Traitsother */
            traitsOther?: boolean | null;
            /** Basement */
            basement?: boolean | null;
            /** Rooftop */
            rooftop?: boolean | null;
            /** Zonecheck */
            zoneCheck?: boolean | null;
            /** Buildingagemin */
            buildingAgeMin?: number | null;
        };
        /** VersionInfo */
        VersionInfo: {
            /** Server */
            server: string;
            /** Ruleshash */
            rulesHash: string;
            /** Programsasof */
            programsAsOf: string;
            classifier: components["schemas"]["ProviderInfo"];
            ranker: components["schemas"]["RankerInfo"];
            /** Confirmthreshold */
            confirmThreshold: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_programs_programs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramsFile"];
                };
            };
        };
    };
    read_program_programs__program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_analyze_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reverse_address_reverse_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_address_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Address"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_building_building_get: {
        parameters: {
            query: {
                sigunguCd: string;
                bjdongCd: string;
                platGbCd: string;
                bun: string;
                ji: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kakao_url_auth_kakao_url_get: {
        parameters: {
            query: {
                redirectUri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kakao_login_auth_kakao_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_profile_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_profile_me_profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
