// 화면 문구 모음 (design.md 10절). 화면 코드에는 문구를 직접 쓰지 않고 여기서 가져온다.
// 존댓말 "-요" 체, 짧게, 한 문장에 한 가지. "해당돼요", "확실히"는 쓰지 않는다.
// 문제 유형 이름은 config/problemTypes.ts, 사업 이름·금액·전화번호는 programs 데이터에서 가져온다.

export const copy = {
  common: {
    next: '다음',
    back: '뒤로',
    retry: '다시 시도',
    callCenter: '행정복지센터에 전화하기',
    callCenterLabel: '주소지 행정복지센터에 전화하기',
    callCenterNoPhone: '행정복지센터 전화번호를 아직 확인하지 못했어요. 가까운 행정복지센터에 직접 문의해 주세요.',
    dontKnow: '잘 모르겠어요',
    yes: '예',
    no: '아니요',
    saved: '저장했어요',
    save: '저장',
    notFoundFallback: '지금은 찾지 못했어요',
    estimateNote: '받을 수 있을 수도 있는 사업이에요. 최종 결정은 상담에서 해요.',
    assetNote: '재산을 포함한 정확한 기준은 상담에서 확인해요.',
  },

  // S0 홈
  home: {
    login: '로그인',
    loginLabel: '카카오로 로그인하기',
    myInfo: '내 정보',
    myInfoLabel: '내 정보 보기',
    loginFailed: '로그인이 잘 안 됐어요. 다시 해 볼게요.',
    themeMenu: '화면 밝기',
    themeMenuLabel: '화면 밝기 바꾸기',
    themeAuto: '자동',
    themeLight: '밝게',
    themeDark: '어둡게',
    logoLabel: '집결 로고',
    emptyVoice: '집에서 고칠 곳을 찍어 주세요',
    takePhoto: '사진 찍기',
    pickPhoto: '앨범에서 고르기',
    retake: '다시 찍기',
    retakeLabel: '사진을 지우고 다시 찍기',
    addCamera: '사진 더 찍기',
    addAlbum: '앨범에서 더 고르기',
    removeThis: '이 사진 지우기',
    removeThisLabel: '지금 보는 사진 지우기',
    maxPhotos: '사진은 3장까지 넣을 수 있어요',
    thumbLabel: (i: number) => `${i}번째 사진 보기`,
    photoLabel: (i: number, n: number) => `고칠 곳 사진 ${n}장 중 ${i}번째`,
    nextDisabledReason: '사진을 넣으면 다음으로 갈 수 있어요',
    processing: '사진을 줄이고 있어요',
    processFailed: '사진을 불러오지 못했어요. 다시 골라 주세요.',
    photoNotice: '사진은 AI가 살펴보려고 외부 AI 서비스로 보내요. 서버에는 저장하지 않아요.',
    cameraDenied: '카메라를 쓸 수 없어요. 앨범에서 골라 보세요.',
    albumDenied: '앨범을 열 수 없어요. 사진 찍기를 눌러 보세요.',
    webCameraUnavailable: '이 기기에서는 카메라를 열 수 없어요. 앨범에서 골라 보세요.',
    savedPrograms: '저장한 지원사업',
    savedCards: '저장한 상담 카드',
    savedEmpty: '아직 저장한 사업이 없어요',
    cardsEmpty: '아직 만든 카드가 없어요',
    savedOn: (d: string) => `${d}에 저장했어요`,
    madeOn: (d: string) => `${d}에 만들었어요`,
    programUnknown: '사업 정보를 확인하고 있어요',
    savedProgramLabel: (name: string) => `저장한 사업 ${name} 열기`,
    savedCardLabel: (name: string) => `상담 카드 ${name} 열기`,
  },

  // S1 가구 정보
  household: {
    stepLabel: (step: number) => `3단계 중 ${step}단계`,
    q1: '몇 명이 함께 사세요?',
    q1More: '5명 이상 직접 입력',
    q1MoreLabel: '5명 이상 인원을 직접 입력하기',
    q1InputLabel: '함께 사는 사람 수',
    q1InputPlaceholder: '숫자만 적어 주세요',
    q1InputApply: '이 인원으로 정하기',
    q1InputMax: '20명까지 적을 수 있어요',
    sizeLabel: (n: number) => `${n}명`,
    sizeSelected: (n: number) => `${n}명 선택됨`,
    q2: '가족이 한 달에 버는 돈은 모두 얼마쯤이에요?',
    q2Pick: '먼저 몇 명이 사는지 골라 주세요',
    q2Over7: '상담에서 확인해요',
    q2Unknown: '잘 모르겠어요',
    q3: '주거급여를 받고 계세요?',
    q4: '어떤 집에 사세요?',
    tenureOwn: '우리 집(자가)',
    tenureRent: '전세·월세',
    tenurePublic: '공공임대(LH·SH)',
    tenureUnknown: '모르겠어요',
    q5: '해당되는 게 있으면 모두 눌러 주세요',
    traitElderly: '65세 이상 가족이 있어요',
    traitDisabled: '장애가 있는 가족이 있어요',
    traitWelfare: '기초수급·차상위예요',
    traitNone: '없어요',
    nextDisabledReason: '위 질문에 모두 답하면 다음으로 갈 수 있어요',
    locationNotice: '주소를 찾으려고 위치를 써요',
  },

  // S2 주소 확인
  address: {
    askHere: '여기 사세요?',
    yes: '예',
    manual: '아니요, 직접 입력할게요',
    searching: '주소를 찾고 있어요',
    searchTitle: '사시는 곳을 찾아볼게요',
    searchPlaceholder: '도로명 주소를 적어 주세요',
    searchLabel: '도로명 주소 검색',
    searchButton: '주소 찾기',
    searchEmpty: '찾는 주소가 없어요. 다시 적어 볼까요?',
    searchFailed: '주소를 찾지 못했어요. 다시 해 볼게요.',
    pickOne: '아래에서 맞는 주소를 골라 주세요',
    jibunPrefix: '지번',
    outOfRegion: '지금은 서울시 노원구 중심으로 안내해요',
    outOfRegionLink: '복지로에서 찾아보기',
    outOfRegionKeep: '그래도 계속 볼게요',
    outOfRegionBack: '다른 주소 찾기',
    outOfRegionLinkLabel: '복지로 누리집을 브라우저에서 열기',
    unitLabel: '동·호수',
    unitPlaceholder: '예: 101동 203호',
    checking: '집 정보를 확인하고 있어요',
    unitOptional: '동·호수는 안 적어도 돼요',
    permissionDenied: '위치를 쓸 수 없어서 주소를 직접 적어 주세요',
    noCoords: '지금 계신 곳을 알 수 없어요. 주소를 직접 적어 주세요',
    lookupFailed: '주소를 찾지 못했어요. 주소를 직접 적어 주세요',
    buildingUnknown: '집을 다 지은 해는 상담에서 확인해요',
  },

  // S3 찾는 중
  searching: {
    first: '사진을 보고 있어요',
    second: '받을 수 있는 지원을 찾고 있어요',
    long: '조금 더 걸리고 있어요',
    logoLabel: '집결 로고',
    failed: '지금은 찾지 못했어요',
  },

  // S4 결과
  results: {
    seenAs: (type: string) => ({ before: '사진을 보니 ', strong: type, after: '예요' }),
    change: '바꾸기',
    changeLabel: '문제 종류 바꾸기',
    confirmAsk: (type: string) => ({ before: '', strong: type, after: '로 보여요. 맞나요?' }),
    confirmYes: '맞아요',
    confirmNo: '아니에요, 고를게요',
    otherVoice: '사진만으로는 잘 모르겠어요',
    otherPick: '아래에서 고쳐야 할 곳을 골라 주세요',
    pickTitle: '어떤 문제인가요?',
    loanPrefix: '보조금이 아니라 대출이에요',
    excludedWhy: (name: string, why: string) => `${name}: ${why}`,
    pickLabel: (name: string) => `${name}로 고르기`,
    retryLabel: '다시 시도하기',
    checkupLabel: (name: string) => `${name}, 먼저 무료 점검을 받아 볼 수 있어요`,
    checkupRow: '먼저 무료 점검을 받아 볼 수 있어요',
    emptyVoice: '지금 조건으로는 찾지 못했어요',
    emptyHelp: '행정복지센터에서 다른 방법을 알려 드려요',
    whyNot: '다른 사업은 왜 없나요?',
    whyNotClose: '접기',
    reasonPrefix: '이유',
    infoChecking: '정보를 확인하고 있어요',
    errorVoice: '지금은 찾지 못했어요',
    changing: '다시 찾고 있어요',
  },

  // S5 사업 상세
  program: {
    infoChecking: '정보를 확인하고 있어요',
    support: '지원 내용',
    amount: '지원 금액',
    amountMore: '금액 설명 펼치기',
    amountMoreLabel: '지원 금액 설명 펼치기',
    amountLess: '접기',
    amountLessLabel: '지원 금액 설명 접기',
    who: '이런 분이 받을 수 있어요',
    whoIncome: '소득',
    whoBuilding: '집을 다 지은 해',
    whoRegion: '지역',
    whoConditions: '그 밖의 조건',
    whyMaybe: '이 가구가 받을 수 있을 수도 있는 이유',
    period: '접수 상태와 기간',
    howTo: '신청 방법',
    phone: '문의 전화',
    phoneChecking: '번호를 확인하고 있어요',
    phoneFallbackHelp: '가까운 행정복지센터에 문의해 주세요',
    toConfirm: '상담에서 확인할 것',
    assetLine: '재산을 포함한 정확한 기준은 상담에서 확인해요',
    source: '출처',
    openSource: (host: string) => `${host} 열기`,
    openSourceLabel: (host: string) => `${host} 누리집을 브라우저에서 열기`,
    asOf: (d: string) => `정보 기준일 ${d}`,
    save: '저장',
    saveLabel: '이 사업 저장하기',
    saved: '저장했어요',
    savedLabel: '저장했어요. 누르면 저장을 취소해요',
    call: '전화하기',
    callLabel: '문의 전화 걸기',
    makeCard: '상담 카드 만들기',
    makeCardLabel: '상담 카드 만들기',
    makingCard: '카드를 만들고 있어요',
    notFound: '찾는 사업이 없어요',
    goBack: '돌아가기',
    goBackLabel: '이전 화면으로 돌아가기',
    loading: '사업 정보를 불러오고 있어요',
  },

  // S6 상담 카드
  card: {
    title: '상담 준비 카드',
    logoLabel: '집결 로고',
    myHome: '우리 집',
    toConfirm: '확인이 필요한 것',
    assetConfirm: '재산을 포함한 소득 기준',
    madeOn: (d: string) => `만든 날 ${d}`,
    saveImage: '이미지로 저장',
    saveImageLabel: '상담 카드를 이미지로 저장하기',
    imageSaved: '이미지로 저장했어요',
    imageDownloaded: '이미지를 내려받았어요',
    imageFailed: '이미지를 저장하지 못했어요. 다시 해 볼게요.',
    share: '보내기',
    shareLabel: '상담 카드 보내기',
    shared: '카드를 보냈어요',
    shareFailed: '카드를 보내지 못했어요. 이미지로 저장해 보세요.',
    call: '전화하기',
    callLabel: '신청처에 전화하기',
    delete: '이 카드 지우기',
    deleteLabel: '이 상담 카드를 지우기',
    deleteAsk: '정말 지울까요?',
    deleteYes: '지우기',
    deleteNo: '그만둘게요',
    notFound: '찾는 카드가 없어요',
    home: '처음 화면으로',
    homeLabel: '처음 화면으로 가기',
    loading: '카드를 불러오고 있어요',
    persons: (n: number) => `가구원 ${n}명`,
    income: (label: string) => `한 달 소득 ${label}`,
    incomeUnknown: '한 달 소득은 상담에서 확인해요',
    benefit: { yes: '주거급여 받고 있어요', no: '주거급여 받지 않아요', unknown: '주거급여는 모르겠어요' },
    tenure: { own: '우리 집(자가)', rent: '전세·월세', public_rent: '공공임대', unknown: '집 형태는 모르겠어요' },
    builtYear: (y: number) => `집을 다 지은 해 ${y}년`,
    builtUnknown: '집을 다 지은 해 확인 필요',
    problem: (name: string) => `문제 ${name}`,
    thumbLabel: '문제 사진',
    permissionDenied: '앨범에 저장할 수 없어요. 보내기를 눌러 보세요.',
    noPhone: '번호를 확인하고 있어요',
    loginVoice: '로그인하면 정보가 지워지지 않아요',
    loginKakao: '카카오로 로그인',
    loginLater: '괜찮아요',
    loginNever: '다시 보지 않기',
  },

  // 로그인 안내 모달, 로그인 돌아오는 화면
  auth: {
    kakaoLabel: '카카오 계정으로 로그인하기',
    laterLabel: '로그인하지 않고 카드 보기',
    neverLabel: '로그인 안내를 다시 보지 않기',
    working: '로그인하고 있어요',
    failed: '로그인이 잘 안 됐어요. 다시 해 볼게요.',
  },

  // S7 내 정보
  profile: {
    title: '내 정보',
    back: '뒤로',
    backLabel: '처음 화면으로 돌아가기',
    signedInAs: (name: string) => `${name} 님으로 로그인했어요`,
    signedInNoName: '로그인했어요',
    signedOut: '로그인하지 않았어요',
    signedOutHelp: '로그인하면 정보가 지워지지 않아요',
    addressTitle: '사는 곳',
    addressNone: '아직 정한 주소가 없어요',
    addressAgain: '주소 다시 찾기',
    addressAgainLabel: '사는 곳 주소를 다시 찾기',
    save: '저장하기',
    saveLabel: '내 정보 저장하기',
    saveDisabledReason: '가구 정보에 모두 답하면 저장할 수 있어요',
    saved: '저장했어요. 다음 검색에서 이 정보로 시작할 수 있어요.',
    savedLocalOnly: '내 기기에 저장했어요. 서버에는 올리지 못했어요.',
    themeTitle: '화면 밝기',
    logout: '로그아웃',
    logoutLabel: '로그아웃하기',
    logoutAsk: '로그아웃할까요?',
    logoutYes: '로그아웃하기',
    logoutNo: '그만둘게요',
    keepAsk: '내 기기에 저장한 사업·카드를 남길까요?',
    keepYes: '남길게요',
    keepNo: '지울게요',
    keepNoLabel: '저장한 사업과 카드를 지우고 로그아웃하기',
  },

  // 저장된 정보로 시작 (S1, S2)
  startFromSaved: {
    ask: '저장된 정보로 시작할까요?',
    yes: '네',
    yesLabel: '저장된 정보로 시작하기',
    no: '아니요, 새로 입력할게요',
  },

  // 실패 화면 공통
  failure: {
    voice: '지금은 찾지 못했어요',
    network: '인터넷이 연결되어 있는지 확인해 주세요',
    timeout: '시간이 조금 오래 걸려요. 다시 해 볼게요.',
    unknown: '잠시 뒤에 다시 해 볼게요',
  },
} as const;

export type Copy = typeof copy;
